language: node_js
node_js: node
script:
- npm run test:lint
- |
  if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_EVENT_TYPE != "cron" ]; then
    echo "Not a Pull Request and on branch master so bumping version";
    frauci-update-version;
    export TRAVIS_TAG=$(frauci-get-version)
  fi
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUI
  - REPO_NAME=typography
  - secure: Ms8j6W8edeEEiue73sMjyeircrPDUcIlq9xxHN35NStolxGB9GVKzPyHlTAyShDO2Jqm48W0cyFa7ketCc3w0v42uF97u28xRtIhjmY2SYsVDj+PeVuckoBJM+2eqvkM94e/2hOjkQLvOc40BIZL9qXafIUp21tXmmYstvUvIk0=
